apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sra1-app1
  labels:
    app.kubernetes.io/name: sra1-app1
    app.kubernetes.io/part-of: sra1-app1-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sra1-app1